class LanguageName {
  final String name;

  LanguageName({required this.name});
}

final List<LanguageName> languages = [
  LanguageName(name: 'English'),
  LanguageName(name: 'Spanish'),
  LanguageName(name: 'French'),
  LanguageName(name: 'German'),
  LanguageName(name: 'Chinese'),
  LanguageName(name: 'Arabic'),
  LanguageName(name: 'Hindi'),
  LanguageName(name: 'Japanese'),
  LanguageName(name: 'Korean'),
  LanguageName(name: 'Russian'),
  LanguageName(name: 'Portuguese'),
  LanguageName(name: 'Italian'),
  LanguageName(name: 'Swedish'),
  LanguageName(name: 'Polish'),
  LanguageName(name: 'Finnish'),
  LanguageName(name: 'Turkish'),
  LanguageName(name: 'Vietnamese'),
  LanguageName(name: 'Thai'),
  LanguageName(name: 'Hebrew'),
  LanguageName(name: 'Indonesian'),
  LanguageName(name: 'Malay'),
  LanguageName(name: 'Danish'),
  LanguageName(name: 'Norwegian'),
  LanguageName(name: 'Greek'),
  LanguageName(name: 'Czech'),
  LanguageName(name: 'Hungarian'),
  LanguageName(name: 'Ukrainian'),
  LanguageName(name: 'Persian'),
  LanguageName(name: 'Romanian'),
  LanguageName(name: 'Bulgarian'),
  LanguageName(name: 'Slovenian'),
  LanguageName(name: 'Slovak'),
  LanguageName(name: 'Croatian'),
  LanguageName(name: 'Lithuanian'),
  LanguageName(name: 'Latvian'),
  LanguageName(name: 'Estonian'),
  LanguageName(name: 'Icelandic'),
  LanguageName(name: 'Swahili'),
  LanguageName(name: 'Tagalog'),
  LanguageName(name: 'Bengali'),
  LanguageName(name: 'Tamil'),
  LanguageName(name: 'Urdu'),
  LanguageName(name: 'Burmese'),
  LanguageName(name: 'Khmer'),
  LanguageName(name: 'Latin'),
  LanguageName(name: 'Irish'),
  LanguageName(name: 'Albanian'),
  LanguageName(name: 'Maltese'),
];
